### ISSUE TITLE
Project Metrics Tab indicates "Nothing to show"

### ISSUE THREAD

**Issue by DidikeM** [b333vv/metricstree#44]
java.lang.ArithmeticException: / by zero
	at org.b333vv.metric.model.metric.value.Value.divide(Value.java:136)
	at org.b333vv.metric.builder.ProjectMetricsSetCalculator.calculateZScore(ProjectMetricsSetCalculator.java:322)
	at org.b333vv.metric.builder.ProjectMetricsSetCalculator.calculateZCoupling(ProjectMetricsSetCalculator.java:225)
	at org.b333vv.metric.builder.ProjectMetricsSetCalculator.calculateQmood(ProjectMetricsSetCalculator.java:103)
	at org.b333vv.metric.builder.ProjectMetricsSetCalculator.calculate(ProjectMetricsSetCalculator.java:97)
	at org.b333vv.metric.task.ProjectMetricTask.run(ProjectMetricTask.java:55)
	at org.b333vv.metric.task.MetricTaskManager.getProjectModel(MetricTaskManager.java:95)
	at org.b333vv.metric.task.ProjectTreeTask.run(ProjectTreeTask.java:51)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by b333vv** [comment]
fixed in 2023.3.0
