### ISSUE TITLE
ActionUpdateThread.OLD_EDT exception

### ISSUE THREAD

**Issue by clutcher** [b333vv/metricstree#50]
On Intellij IDEA 2024.2.1 plugin is constantly throwing same exception, while clicking around in plugin UI.

```java
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.b333vv.metric.actions.RefreshMetricsTreeAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.b333vv.metricstree]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by b333vv** [comment]
Fixed in version 2024.1.1.
